### ISSUE TITLE
加密时报错

### ISSUE THREAD

**Issue by sayri23** [hexstr/FGOAssetsModifyTool#5]
再解密后重新加密时会有如下错误，每个文件都是这样
output buffer too short
   at Org.BouncyCastle.Crypto.Paddings.PaddedBufferedBlockCipher.DoFinal(Byte[] output, Int32 outOff)
   at FGOAssetsModifyTool.CatAndMouseGame.CatHomeMain(Byte[] data, Byte[] home, Byte[] info, Boolean isCompress) in Y:\Workspace\FGOAssetsModifyTool\FGOAssetsModifyTool\CatAndMouseGame.cs:line 286
Value cannot be null. (Parameter 'bytes')
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at FGOAssetsModifyTool.Program.DisplayMenuAsync() in Y:\Workspace\FGOAssetsModifyTool\FGOAssetsModifyTool\Program.cs:line 93

**Comment by hexstr** [comment]
日服的解密多了一道工序，我只处理了加密

**Comment by sayri23** [comment]
我在想能不能用解密了的日服资源按国服的方式加密来替换掉国服的资源

**Comment by hexstr** [comment]
可以是可以但是文件有crc校验，你要自己处理一下
@sayri23
