### ISSUE TITLE
解码错误

### ISSUE THREAD

**Issue by hal-tech-lab** [hexstr/FGOAssetsModifyTool#6]
似乎FGO7周年纪念中实施的bin文件不能被解密。
日文版 2.58.0
```
com.aniplex.fategrandorder\files\data\d713\Android\0092fc7be2c337fb3aa38e49d0378b143c013bc9.bin
pad block corrupted
   at Org.BouncyCastle.Crypto.Paddings.Pkcs7Padding.PadCount(Byte[] input)
   at Org.BouncyCastle.Crypto.Paddings.PaddedBufferedBlockCipher.DoFinal(Byte[] output, Int32 outOff)
   at FGOAssetsModifyTool.CatAndMouseGame.MouseHomeMain(Byte[] data, Byte[] home, Byte[] info, Boolean isCompress) in Y:\Workspace\FGOAssetsModifyTool\FGOAssetsModifyTool\CatAndMouseGame.cs:line 331
MouseHomeMain failed
Value cannot be null. (Parameter 'bytes')
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at FGOAssetsModifyTool.Program.DisplayMenuAsync() in Y:\Workspace\FGOAssetsModifyTool\FGOAssetsModifyTool\Program.cs:line 130
```

DeepL translation used

**Comment by hal-tech-lab** [comment]
对不起，我一定是有点生气了。 我刚刚又试了一次，成功了。
