### ISSUE TITLE
pad block corrupted

### ISSUE THREAD

**Issue by iruiruru** [hexstr/FGOAssetsModifyTool#7]
出现了pad block corrupted 解密后可查看的文件只有很小一部分

**Comment by hexstr** [comment]
把`Android/gamedata`和一堆`*.json`删了重新生成

**Comment by iruiruru** [comment]
感谢你的回复 但问题依旧存在
pad block corrupted
   at Org.BouncyCastle.Crypto.Paddings.Pkcs7Padding.PadCount(Byte[] input)
   at Org.BouncyCastle.Crypto.Paddings.PaddedBufferedBlockCipher.DoFinal(Byte[] output, Int32 outOff)
   at FGOAssetsModifyTool.CatAndMouseGame.MouseHomeMain(Byte[] data, Byte[] home, Byte[] info, Boolean isCompress) in Y:\Workspace\FGOAssetsModifyTool\FGOAssetsModifyTool\CatAndMouseGame.cs:line 331
MouseHomeMain failed
Value cannot be null. (Parameter 'bytes')
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at FGOAssetsModifyTool.Program.DisplayMenuAsync() in Y:\Workspace\FGOAssetsModifyTool\FGOAssetsModifyTool\Program.cs:line 130

**Comment by hexstr** [comment]
@iruiruru 文件名发给我看看

**Comment by iruiruru** [comment]
使用的是net6.0版本 文件是日服2.58.0版本

**Comment by iruiruru** [comment]
以此运行3->7->4->6->0后 将d713中的文件导入进Android文件夹 输入2运行 这个过程是否有误

**Comment by iruiruru** [comment]
运行3->7->4->6->0后 将d713中的文件导入进Android文件夹 输入2运行 这个过程是否有误

**Comment by hexstr** [comment]
@iruiruru 我是问哪个文件解密出错

**Comment by iruiruru** [comment]
06ff395cee2b2000c5e078a6da5c2e0f0960dcc2.bin

**Comment by hexstr** [comment]
怕不是key还没更新，我在`AssetStorage.txt`里也没有找到这个文件

**Comment by hexstr** [comment]
修好了，多了个`-1`最后一行没处理

**Comment by iruiruru** [comment]
用了下没问题了 非常感谢



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年08月07日 21:29 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [hexstr/FGOAssetsModifyTool] pad block corrupted (Issue #7) |

修好了，多了个-1最后一行没处理
